name: Build luci-app-adguardhome

permissions:
  contents: write   # 需要写权限才能发布 Release

on:
  push:
    branches:
      - main
    paths:
      - '**/Makefile'
  pull_request:
  workflow_dispatch:
  release:
    types: [created]

env:
  TZ: Asia/Shanghai
  SDK_VER: "24.10"
  LUCI_VER: "24.10"
  SDK_URL: "https://downloads.openwrt.org/releases/24.10.3/targets/x86/64/openwrt-sdk-24.10.3-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup build environment
        run: |
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android
          echo "Install environment packages"
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget zstd
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Cache dl
        uses: actions/cache@v4
        with:
          path: sdk/dl
          key: ${{ runner.os }}-openwrt-dl-${{ env.SDK_VER }}
          restore-keys: |
            ${{ runner.os }}-openwrt-dl-

      - name: Download and extract OpenWrt SDK
        run: |
          mkdir -p sdk
          find sdk -mindepth 1 -maxdepth 1 ! -name dl -exec rm -rf {} +
          
          cd sdk
          wget -q $SDK_URL -O sdk.tar.zst
          tar --use-compress-program=unzstd -xf sdk.tar.zst --strip-components=1

      - name: Prepare feeds
        run: |
          cd sdk
          ln -s $GITHUB_WORKSPACE package/luci-app-adguardhome
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          #--------------------------------------begin_patches------------------------------------------
          echo "Start applying the patch"
          rm -rf temp_resp
          git clone -b master --single-branch https://github.com/openwrt/packages.git temp_resp
          cd temp_resp
          git checkout 2b99cd7d7637da0f152da378994f699aaf0dd44d
          cd ..
          echo "update golang version"
          rm -rf feeds/packages/lang/golang
          cp -r temp_resp/lang/golang feeds/packages/lang
          echo "update rust version"
          rm -rf feeds/packages/lang/rust
          cp -r temp_resp/lang/rust feeds/packages/lang
          rm -rf temp_resp
          echo "Patch application completed"
          #--------------------------------------end_patches--------------------------------------------
      - name: Generate luci.mk patch
        id: gen_luci_patch
        uses: Jackie264/actions-repo/.github/actions/gen-luci-mk-patch@v1.0.0
          
      - name: Build luci-app-adguardhome
        run: |
          cd sdk
          make defconfig
          make package/luci-app-adguardhome/{clean,compile} -j$(nproc) V=s
        
      - name: Collect artifacts
        run: |
          mkdir -p output
          find sdk/bin/packages/ -name "luci-app-adguardhome*.ipk" -exec cp {} output/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-adguardhome-${{ env.SDK_VER }}
          path: output/*.ipk

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: luci-app-adguardhome-${{ env.SDK_VER }}
          path: release-ipk

      - name: Parse version from ipk
        id: parse
        uses: Jackie264/actions-repo/.github/actions/parse-ipk-file@v1.0.0
        with:
          file: release-ipk/luci-app-adguardhome*.ipk

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.parse.outputs.ver }}
          name: luci-app-adguardhome v${{ steps.parse.outputs.ver }}
          files: release-ipk/*.ipk
